name: Run Claude Prompt via OAuth

on:
  schedule:
    # Runs at 5:30am, 10:30am, 3:30pm, 8:30pm IST (0:00, 5:00, 10:00, 15:00 UTC)
    - cron: '0 0,5,10,15 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-claude:
    runs-on: ubuntu-latest
    steps:
      - name: Run Claude Code with OAuth token
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: "hello"
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}