name: Run Claude Prompt via OAuth

on:
  schedule:
    # Runs at 5:30am, 10:30am, 3:30pm, 8:30pm IST (0:00, 5:00, 10:00, 15:00 UTC)
    - cron: '0 0,5,10,15 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-claude:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Claude Code
        run: |
          npm install -g @anthropic-ai/claude-code
          
      - name: Configure Claude OAuth
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run: |
          # Create Claude config directory
          mkdir -p ~/.claude
          
          # Set up OAuth token configuration
          echo '{"oauth_token": "'$CLAUDE_CODE_OAUTH_TOKEN'"}' > ~/.claude/oauth_token.json
          
      - name: Run Claude Code Prompt
        run: |
          # Run Claude with the "hello" prompt
          claude --print "hello" --model sonnet
